### ISSUE TITLE
The EAIntroDelegate is not being called.

### ISSUE THREAD

**Issue by JeanPierreFig** [ealeksandrov/EAIntroView#173] opened 2016-06-26 23:29 UTC

**Comment by JeanPierreFig** [comment] 2016-06-26 23:33
ok go it working :) The example project I Just download uses a older version of the Delegates 

`- (void)introDidFinish:(EAIntroView *)introView wasSkipped:(BOOL)wasSkipped{}`

This one worked

**Comment by ealeksandrov** [comment] 2016-06-27 07:05
Yeah, we should fix that :)
Closing as duplicate of #167

**Closed by ealeksandrov** 2016-06-27 07:05 UTC
