### ISSUE TITLE
using pageWithCustomViewFromNibNamed which loads Nib file with image view control inside it fails

### ISSUE THREAD

**Issue by velchev** [ealeksandrov/EAIntroView#106] opened 2015-04-23 07:21 UTC
Hello my app is craching when I load the Nib file if the file have an image inside it. It only works without that.
Here is my code example:
 EAIntroPage *page1 = [EAIntroPage pageWithCustomViewFromNibNamed:@"IntroView3"];
        page1.bgImage = [UIImage imageNamed:@"bg2"];
        EAIntroPage *page2 = [EAIntroPage pageWithCustomViewFromNibNamed:@"View"];
        page2.bgImage = [UIImage imageNamed:@"bg2"];
        EAIntroPage *page3 = [EAIntroPage pageWithCustomViewFromNibNamed:@"View"];
        page3.bgImage = [UIImage imageNamed:@"bg2"];
        
        EAIntroView *intro = [[EAIntroView alloc] initWithFrame:self.view.bounds andPages:@[page1,page2, page3]];
        
        [intro showInView:self.view animateDuration:1.0];

Here is the log:
2015-04-23 08:22:38.752 MatesLocator[10601:1081068] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 4 beyond bounds [0 .. 3]'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010fa9ea75 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010f737bb7 objc_exception_throw + 45
	2   CoreFoundation                      0x000000010f989893 -[__NSArrayM objectAtIndex:] + 227
	3   UIKit                               0x000000010e198e11 _UIViewTopDownSubtreeTraversal + 193
	4   UIKit                               0x000000010e7cbfd6 -[UIView(UIConstraintBasedLayout_EngineDelegate) _invalidateSystemLayoutSizeFittingSizeAtEngineDelegateLevel] + 128
	5   Foundation                          0x000000010d7cef4f -[NSISEngine tryToAddConstraintWithMarker:expression:integralizationAdjustment:mutuallyExclusiveConstraints:] + 915
	6   Foundation                          0x000000010d959af8 -[NSLayoutConstraint _addLoweredExpression:toEngine:integralizationAdjustment:lastLoweredConstantWasRounded:mutuallyExclusiveConstraints:] + 275
	7   Foundation                          0x000000010d7c36aa -[NSLayoutConstraint _addToEngine:integralizationAdjustment:mutuallyExclusiveConstraints:] + 220
	8   UIKit                               0x000000010e7c8ed5 __57-[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:]_block_invoke_2 + 474
	9   Foundation                          0x000000010d7d12fe -[NSISEngine withBehaviors:performModifications:] + 155
	10  UIKit                               0x000000010e7c8cdb __57-[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:]_block_invoke + 452
	11  UIKit                               0x000000010e7c8aee -[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:] + 197
	12  UIKit                               0x000000010e7c8dd4 __57-[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:]_block_invoke_2 + 217
	13  Foundation                          0x000000010d7d12fe -[NSISEngine withBehaviors:performModifications:] + 155
	14  UIKit                               0x000000010e7c8cdb __57-[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:]_block_invoke + 452
	15  UIKit                               0x000000010e7c8aee -[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:] + 197
	16  UIKit                               0x000000010e7c8dd4 __57-[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:]_block_invoke_2 + 217
	17  Foundation                          0x000000010d7d12fe -[NSISEngine withBehaviors:performModifications:] + 155
	18  UIKit                               0x000000010e7c8cdb __57-[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:]_block_invoke + 452
	19  UIKit                               0x000000010e7c8aee -[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:] + 197
	20  UIKit                               0x000000010e1c2edb -[UIScrollView _switchToLayoutEngine:] + 69
	21  UIKit                               0x000000010e7c8dd4 __57-[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:]_block_invoke_2 + 217
	22  Foundation                          0x000000010d7d12fe -[NSISEngine withBehaviors:performModifications:] + 155
	23  UIKit                               0x000000010e7c8cdb __57-[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:]_block_invoke + 452
	24  UIKit                               0x000000010e7c8aee -[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:] + 197
	25  UIKit                               0x000000010e7c8dd4 __57-[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:]_block_invoke_2 + 217
	26  Foundation                          0x000000010d7d12fe -[NSISEngine withBehaviors:performModifications:] + 155
	27  UIKit                               0x000000010e7c8cdb __57-[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:]_block_invoke + 452
	28  UIKit                               0x000000010e7c8aee -[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:] + 197
	29  UIKit                               0x000000010e7c8761 -[UIView(AdditionalLayoutSupport) _initializeHostedLayoutEngine] + 404
	30  UIKit                               0x000000010e7bd681 -[UIView(UIConstraintBasedLayout) _layoutEngine_windowDidChange] + 127
	31  UIKit                               0x000000010e1b5cf5 -[UIView(Internal) _didMoveFromWindow:toWindow:] + 207
	32  UIKit                               0x000000010e1b5ede -[UIView(Internal) _didMoveFromWindow:toWindow:] + 696
	33  UIKit                               0x000000010e1ae962 __45-[UIView(Hierarchy) _postMovedFromSuperview:]_block_invoke + 125
	34  UIKit                               0x000000010e1ae8d6 -[UIView(Hierarchy) _postMovedFromSuperview:] + 437
	35  UIKit                               0x000000010e1b879b -[UIView(Internal) _addSubview:positioned:relativeTo:] + 1604
	36  MatesLocator                        0x000000010d0ab106 -[ECSlidingViewController setTopViewController:] + 1718
	37  MatesLocator                        0x000000010d0aa4d2 __56-[MenuViewController tableView:didSelectRowAtIndexPath:]_block_invoke + 306
	38  MatesLocator                        0x000000010d0adc53 __74-[ECSlidingViewController anchorTopViewOffScreenTo:animations:onComplete:]_block_invoke210 + 67
	39  UIKit                               0x000000010e1b3963 -[UIViewAnimationBlockDelegate _didEndBlockAnimation:finished:context:] + 326
	40  UIKit                               0x000000010e19b6ca -[UIViewAnimationState sendDelegateAnimationDidStop:finished:] + 209
	41  UIKit                               0x000000010e19ba00 -[UIViewAnimationState animationDidStop:finished:] + 76
	42  QuartzCore                          0x000000010de8565e _ZN2CA5Layer23run_animation_callbacksEPv + 308
	43  libdispatch.dylib                   0x00000001100b4614 _dispatch_client_callout + 8
	44  libdispatch.dylib                   0x000000011009ca1c _dispatch_main_queue_callback_4CF + 1664
	45  CoreFoundation                      0x000000010fa06749 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	46  CoreFoundation                      0x000000010f9c962b __CFRunLoopRun + 2043
	47  CoreFoundation                      0x000000010f9c8bc6 CFRunLoopRunSpecific + 470
	48  GraphicsServices                    0x0000000111438a58 GSEventRunModal + 161
	49  UIKit                               0x000000010e141580 UIApplicationMain + 1282
	50  MatesLocator                        0x000000010d0a8573 main + 115
	51  libdyld.dylib                       0x00000001100e9145 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by ealeksandrov** [comment] 2015-04-23 08:58
Related with #100?

Thanks for sharing, I'll look into it.

**Comment by carrchr** [comment] 2015-05-06 21:05
+1 I also get this issue if I upgrade from 1.0.2 to 1.0.6
`	EAIntroPage *page3 = [EAIntroPage pageWithCustomViewFromNibNamed:@"Intro3"];`

**Comment by ealeksandrov** [comment] 2015-05-07 16:52
Closing as duplicate of #100

**Closed by ealeksandrov** 2015-05-07 16:52 UTC
Labels: Bug
