### ISSUE TITLE
Not works in iOS8.1

### ISSUE THREAD

**Issue by amarianno** [ealeksandrov/EAIntroView#154] opened 2016-01-28 13:51 UTC
I used last version 2.8.1 and my app in iOS 8.1 get crash : Thread 1: EXC_BREAKPOINT (code=EXC_I386)

after downgrade to 2.7 app works fine.

**Comment by ealeksandrov** [comment] 2016-01-28 14:59
Can you tell what line is causing crash?

**Comment by ealeksandrov** [comment] 2016-01-28 15:01
You can also downgrade version-by-version to narrow down changeset to debug.
Have you tried 2.8.0, 2.7.1, 2.7.2, 2.7.3, 2.7.4?

**Comment by ealeksandrov** [comment] 2016-04-12 15:43
Can't reproduce on iOS Simulator 8.1 and latest EAIntroView version.
After multiple test runs I seen crash or simulator launch once, but that was fixed by simple project clean.

**Closed by ealeksandrov** 2016-04-12 15:43 UTC
